name: Kubectl Setup

on:
  workflow_call:
    inputs:
      kubeconfig_secret:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Write kubeconfig
        run: echo "${{ secrets[inputs.kubeconfig_secret] }}" > kubeconfig
        shell: bash

      - name: Upload kubeconfig
        uses: actions/upload-artifact@v4
        with:
          name: kubeconfig
          path: kubeconfig