name: 'Kubectl Deploy'
description: 'Deploy Kubernetes manifests and restart deployment'

inputs:
  manifests:
    description: 'Space-separated list of manifest files to apply'
    required: true
  deployment_name:
    description: 'Name of the deployment to restart'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download kubeconfig
      uses: actions/download-artifact@v4
      with:
        name: kubeconfig
        path: .

    - name: Apply Kubernetes manifests
      run: |
        for manifest in ${{ inputs.manifests }}; do
          kubectl apply -f "$manifest"
        done
      shell: bash
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Rollout restart deployment
      run: kubectl rollout restart deployment/${{ inputs.deployment_name }}
      shell: bash
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig