name: Kubectl Deploy

on:
  workflow_call:
    inputs:
      manifests:
        required: true
        type: string
        description: "Space-separated list of manifest files to apply"
      deployment_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/kubectl-deploy
        with:
          manifests: ${{ inputs.manifests }}
          deployment_name: ${{ inputs.deployment_name }}