name: Kubectl Deploy

on:
  workflow_call:
    inputs:
      manifests:
        required: true
        type: string
        description: "Space-separated list of manifest files to apply"
      deployment_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download kubeconfig
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig
          path: .

      - name: Apply Kubernetes manifests
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          for manifest in ${{ inputs.manifests }}; do
            kubectl apply -f "$manifest"
          done
        shell: bash

      # If we're not deploying a new deployment with a new version, we may want to restart it to pick up changes
      - name: Rollout restart deployment
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl rollout restart deployment/${{ inputs.deployment_name }}
        shell: bash